### ISSUE TITLE
filter/lookup selector issue

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/hapa#23]
If there is no lookup-filter set, but the search field populated, the filter does not work; see e.g. 
https://hapa.acdh-dev.oeaw.ac.at/archiv/hapaplacename/?name=Ha&name_lookup=&alternative_names=&alternative_names_lookup=&wortbildung=&wortbildung_lookup=&etymology=&etymology_lookup=&syntax=&syntax_lookup=&comment=&comment_lookup=&internal_comment=&internal_comment_lookup=&unclear=unknown&Filter=Search

Not sure how this could be solved easily (but I also didn't look into it); anyhow it would be nice if only those filter params were sent which are actually set, because this would make the URL much more readable, e.g. only https://hapa.acdh-dev.oeaw.ac.at/archiv/hapaplacename/?name=Ha

**Comment by linxOD** [comment]
pushed a quick fix. The default empty lookup filter is disabled now. It will take the first element of the lookup list which is icontains.
Regarding the URL I have to find out how this works.

**Comment by linxOD** [comment]
For future reference, fix in progress

https://stackoverflow.com/questions/5904437/jquery-how-to-remove-blank-fields-from-a-form-before-submitting

https://stackoverflow.com/questions/46834539/removing-unnecessary-filters-from-url-django-filter
