### ISSUE TITLE
add customizable virtual keyboard

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/hapa#29]
something like in https://mecmua.acdh.oeaw.ac.at/corpus.html
maybe based on some more up to date js-libs, e.g. https://github.com/Mottie/Keyboard

**Comment by simar0at** [comment]
https://github.com/simar0at/virtual-keyboard ~ what is used in mecmua

**Comment by csae8092** [comment]
going with https://furcan.github.io/KioskBoard/; only problem is that actual keyboard does not work; although setting `allowRealKeyboard: true,`

**Comment by csae8092** [comment]
filed ticket https://github.com/furcan/KioskBoard/issues/24
